from app.database import get_database
from app.models.receipt import ReceiptSchema
import asyncio

async def cleanup_expenses():
    db = get_database()
    
    # 1. Delete expenses with "HSCODE" or "Total" in description (generated by OCR)
    # Only target those with a receipt_id to be safe
    result = await db.expenses.delete_many({
        "receipt_id": {"$ne": None},
        "$or": [
            {"description": {"$regex": "HSCODE", "$options": "i"}},
            {"description": {"$regex": "Total", "$options": "i"}},
            {"description": {"$regex": "Subtotal", "$options": "i"}},
            {"description": {"$regex": "Tax", "$options": "i"}},
            {"description": ""} # Empty descriptions
        ]
    })
    
    print(f"Deleted {result.deleted_count} junk expense items.")
    
    # 2. Clean up descriptions of remaining items (remove "1). ", etc)
    expenses = await db.expenses.find({"receipt_id": {"$ne": None}}).to_list(1000)
    
    cleaned_count = 0
    import re
    
    for exp in expenses:
        original = exp.get("description", "")
        # Remove leading numbers/bullets
        cleaned = re.sub(r'^[\d]+\s*[).]*\s*', '', original)
        cleaned = re.sub(r'^[^\w\s]+', '', cleaned).strip()
        
        if cleaned != original and len(cleaned) > 2:
            await db.expenses.update_one(
                {"_id": exp["_id"]},
                {"$set": {"description": cleaned}}
            )
            cleaned_count += 1
            
    print(f"Cleaned descriptions for {cleaned_count} items.")

if __name__ == "__main__":
    from app.main import app # Bootstrap app to connect to DB
    asyncio.run(cleanup_expenses())
